In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# 1) List Operations

In [3]:
a,d,g = 11,31,87
d

31

In [8]:
arr = [10,11,12,13,14,95,33,65]
arr[-1]
len(arr)

8

In [9]:
arr.append("Say..Hello!")
arr

[10, 11, 12, 13, 14, 95, 33, 65, 'Say..Hello!']

In [10]:
del arr[0]
arr

[11, 12, 13, 14, 95, 33, 65, 'Say..Hello!']

In [11]:
arr.remove(33)
arr

[11, 12, 13, 14, 95, 65, 'Say..Hello!']

In [12]:
arr.pop(2)
arr

[11, 12, 14, 95, 65, 'Say..Hello!']

In [13]:
arr.pop()
arr

[11, 12, 14, 95, 65]

In [15]:
"I\'m a good girl, " * 3

"I'm a good girl, I'm a good girl, I'm a good girl, "

In [26]:
a1=[1,3,2,4]
a2=[5,6,7,8]
print(a1+a2)
print(1 in a1)
3 not in a1

[1, 3, 2, 4, 5, 6, 7, 8]
True


False

In [23]:
def first_fun():
    a=10
    b=20
    c=a+b
    return c
    
call_fun= first_fun()
print(call_fun)

30


In [31]:
# yield function
def generator():
    for i in range(6):
        yield i+2
        
kb = generator()
for d in kb:
     print(d)

2
3
4
5
6
7


# Tuple

In [32]:
tup1 = (11,1,2,45,(10,12,14),['hi','how','are','you'])
tup1

(11, 1, 2, 45, (10, 12, 14), ['hi', 'how', 'are', 'you'])

In [39]:
print(tup1[-1][0])
print(tup1[-1][-1])
tup1[0]

hi
you


11

In [50]:
tup2 = (101,876,999,546,223,571,942,999)
print(tup2)
print("The length is ",len(tup2))
print(min(tup2))
print(max(tup2))
print(sorted(tup2))

(101, 876, 999, 546, 223, 571, 942, 999)
The length is  8
101
999
[101, 223, 546, 571, 876, 942, 999, 999]


In [47]:
#unpacking tuple
mark1,mark2, mark3,mark4,mark5,mark6,mark7 = tup2
print(mark1,"", mark6)

101  571


In [48]:
print(('Hey Karthika',)*2)

('Hey Karthika', 'Hey Karthika')


In [53]:
tup2.count(999)
tup2.index(223)

4

# Sets

In [56]:
set1= {1,2,3,4,(10,11,12)}
set1

{(10, 11, 12), 1, 2, 3, 4}

In [57]:
set2 = set([98,97,96,95])
set2

{95, 96, 97, 98}

In [61]:
set2.add(10)
set2

{10, 95, 96, 97, 98}

In [62]:
set2.update([98,23,45,97])
set2

{10, 23, 45, 95, 96, 97, 98}

In [68]:
set1.remove(3)
set1

{(10, 11, 12), 1, 2}

In [70]:
set1.discard(1)
set1

{(10, 11, 12), 2}

In [72]:
set1.pop()

2

In [73]:
set1|set2

{(10, 11, 12), 10, 23, 45, 95, 96, 97, 98}

In [74]:
set1.clear()

In [76]:
set1.update([10,23,11,54,96,54])
set1

{10, 11, 23, 54, 96}

In [77]:
set1&set2

{10, 23, 96}

In [80]:
set1^(set2) # symmetric difference

{11, 45, 54, 95, 97, 98}

In [82]:
sorted(set2) 

[10, 23, 45, 95, 96, 97, 98]

# Dictionary 

In [8]:
dict1 ={'Name':'karthika', 'lastname':'selvaraj','age':21,'position':'professional data scientist', 'specification':'sprots'}
dict1

{'Name': 'karthika',
 'lastname': 'selvaraj',
 'age': 21,
 'position': 'professional data scientist',
 'specification': 'sprots'}

In [5]:
dict1['Name']

'karthika'

In [9]:
dict1.pop('lastname')
dict1

{'Name': 'karthika',
 'age': 21,
 'position': 'professional data scientist',
 'specification': 'sprots'}

In [121]:
dict1.popitem()

('specification', 'sprots')

In [122]:
dict2 = { a: a+10 for a in range(6)}
dict2

{0: 10, 1: 11, 2: 12, 3: 13, 4: 14, 5: 15}

In [123]:
dict2[0]

10

In [10]:
dict1

{'Name': 'karthika',
 'age': 21,
 'position': 'professional data scientist',
 'specification': 'sprots'}

In [11]:
dict1.update({'Salary':'100000 permonth'})
dict1

{'Name': 'karthika',
 'age': 21,
 'position': 'professional data scientist',
 'specification': 'sprots',
 'Salary': '100000 permonth'}

In [132]:
dict1['Salary'] = '100000 per month'
dict1

{'Name': 'karthika',
 'age': 21,
 'position': 'professional data scientist',
 'Salary': '100000 per month'}

# String

In [14]:
sr1 = "Hey, I\'m a Data Scientist"
sr1

"Hey, I'm a Data Scientist"

In [12]:
sr2 = '''hey mate! Do you know onething,after a lots of hardwork and practice,I acheive my DATA SCEIENCE career :)..'''
sr2

'hey mate! Do you know onething,after a lots of hardwork and practice,I acheive my DATA SCEIENCE career :)..'

In [140]:
#Enumerate
sr3="hey you"
list(enumerate(sr3))

[(0, 'h'), (1, 'e'), (2, 'y'), (3, ' '), (4, 'y'), (5, 'o'), (6, 'u')]

In [141]:
sr2.upper()

' HEY MATE! DO YOU KNOW ONETHING, AFTER A LOTS OF HARDWORK AND PRACTICE,I ACHEIVE MY DATA SCEIENCE CAREER :)..'

In [142]:
sr2.lower()

' hey mate! do you know onething, after a lots of hardwork and practice,i acheive my data sceience career :)..'

In [152]:
sr2.title()

' Hey Mate! Do You Know Onething,After A Lots Of Hardwork And Practice,I Acheive My Data Sceience Career :)..'

In [153]:
sr2

' hey mate! Do you know onething,after a lots of hardwork and practice,I acheive my DATA SCEIENCE career :)..'

In [155]:
sr2.swapcase()

' HEY MATE! dO YOU KNOW ONETHING,AFTER A LOTS OF HARDWORK AND PRACTICE,i ACHEIVE MY data sceience CAREER :)..'

In [157]:
sr2.strip()

'hey mate! Do you know onething,after a lots of hardwork and practice,I acheive my DATA SCEIENCE career :)..'

In [158]:
sr2.title()

' Hey Mate! Do You Know Onething,After A Lots Of Hardwork And Practice,I Acheive My Data Sceience Career :)..'

In [159]:
sr2.capitalize()

' hey mate! do you know onething,after a lots of hardwork and practice,i acheive my data sceience career :)..'

In [19]:
sr2.replace('hey','looooo')
sr2

'hey mate! Do you know onething,after a lots of hardwork and practice,I acheive my DATA SCEIENCE career :)..'

In [177]:
sr1[0:10]

"Hey, I'm a"

# Other important operations

In [178]:
print("{},{} and {}".format(1,2,3))

1,2 and 3


In [189]:
v1= 100
v2=26.61
v3=10
print(isinstance(v1, int))
print(isinstance(v2, float))
print(isinstance(v3, complex))

True
True
False


In [192]:
# Iterator
li1 = [10,11,12,13,14,15]
ir = iter(li1)
print(next(ir))
print(next(ir))
print(next(ir))

10
11
12


In [201]:
# Iterating Odd number
class odd_iter:
    '''Iterating odd numbers required times'''
    def __iter__(self):
        self.num=1
        return self
    def __next__(self):
        num=self.num
        self.num   += 2
        return num
    
print(odd_iter.__doc__)
i =odd_iter()
r =iter(i)
print(next(r))
print(next(r))
print(next(r))
print(next(r))

Iterating odd numbers required times
1
3
5
7


In [206]:
li2 = [1,2,3,4,5]
for i in li2:
    print(i, end=" ")
    print("Hello")

1 Hello
2 Hello
3 Hello
4 Hello
5 Hello


In [20]:
for r1 in range(10,-1,-1):
     print(r1)

10
9
8
7
6
5
4
3
2
1
0


# Function Argument

In [220]:
def hello(a,b):
    print("Say Hello to ", a,"and",b)

hello('jami','mami')

Say Hello to  jami and mami


In [224]:
def new_fun(w,e):
    if w<e:
        return w
    else:
        return e

new_fun(100463,76541)

76541

In [229]:
def sum_all(*args):
    su = 0
    for i in args:
        su += i
    return su
    
sum_all(10,10,10,10,90)

130

In [256]:
for i in range(4):
    aw= [0]
    print(aw*4, end=" ")


[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 0] 

# Try & Expect

In [258]:
try:
    a,b=198,0
    c= a/b
    print(c)
except ZeroDivisionError:
    print("Can\'t divide")

Can't divide


In [234]:
try:
    a='hey'
    b=int(a)
    print(b)
except:
    print("DataType Error")

DataType Error


# Numpy 

In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
type(arr1)

numpy.ndarray

In [27]:
arr1.shape
arr1.ndim

2

In [35]:
arr1[:,1]

array([2, 5])

In [39]:
for i in np.arange(25,20,-1):
    print(i)

25
24
23
22
21


In [41]:
arr2 = arr1.copy()
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [58]:
gp1=np.random.rand(3,4)
gp1

array([[0.94490685, 0.82210961, 0.87029091, 0.06377436],
       [0.34748774, 0.38883826, 0.81570401, 0.08674522],
       [0.12826639, 0.7551113 , 0.77619424, 0.52936522]])

In [62]:
gp=np.random.randn(3,4)
gp

array([[-2.30666551,  0.71872843,  0.64087887,  0.26498262],
       [ 0.38317319,  0.20949616, -0.13646187,  0.06648398],
       [-0.30850436,  0.98413567,  0.16533689, -0.60344519]])

In [60]:
np.random.randint(2,6,(3,3))

array([[2, 5, 5],
       [4, 5, 3],
       [5, 3, 4]])

In [66]:
arr2[1,1:] = 750
arr2

array([[  1,   2,   3],
       [  4, 750, 750]])

In [68]:
arr2<120

array([[ True,  True,  True],
       [ True, False, False]])

In [71]:
arr2[arr2<120] = 145
arr2

array([[145, 145, 145],
       [145, 750, 750]])

In [73]:
arr2[arr2>145]

array([750, 750])

In [75]:
np.ones((6,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [80]:
np.zeros((5,4)).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
re = np.random.randint(3,10,(2,6))
re

array([[8, 7, 9, 7, 9, 4],
       [3, 9, 9, 8, 4, 8]])

In [85]:
re.reshape(4,3)

array([[8, 7, 9],
       [7, 9, 4],
       [3, 9, 9],
       [8, 4, 8]])

In [87]:
re.reshape(12,1)

array([[8],
       [7],
       [9],
       [7],
       [9],
       [4],
       [3],
       [9],
       [9],
       [8],
       [4],
       [8]])